### ISSUE TITLE
`Index out of range` error

### ISSUE THREAD

**Issue by JoshLoecker** [DrunkOnBytes/flutter_collapsible_sidebar#49]
Hi, I am trying to create a simply three-item sidebar, but I am receiving the following error. I have three items in the sidebar, and it seems that the fourth item (index 3) is trying to be accessed. Any ideas on why this might be happening? Thanks for any help!

```dart
======== Exception caught by gesture ===============================================================
The following IndexError was thrown while handling a gesture:
RangeError (index): Index out of range: index should be less than 3: 3

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 581:7                 _get]
packages/collapsible_sidebar/collapsible_sidebar.dart 392:44                      <fn>
packages/flutter/src/gestures/recognizer.dart 253:24                              invokeCallback
packages/flutter/src/gestures/tap.dart 627:11                                     handleTapUp
packages/flutter/src/gestures/tap.dart 306:5                                      [_checkUp]
packages/flutter/src/gestures/tap.dart 276:7                                      acceptGesture
packages/flutter/src/gestures/arena.dart 163:12                                   sweep
packages/flutter/src/gestures/binding.dart 464:20                                 handleEvent
packages/flutter/src/gestures/binding.dart 440:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 336:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 395:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 357:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 314:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 295:7                                  [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1183:13                               invoke1
lib/_engine/engine/platform_dispatcher.dart 243:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 156:39                                    [_onPointerData]
lib/_engine/engine/pointer_binding.dart 689:20                                    <fn>
lib/_engine/engine/pointer_binding.dart 620:14                                    <fn>
lib/_engine/engine/pointer_binding.dart 303:16                                    loggedHandler
lib/_engine/engine/pointer_binding.dart 188:80                                    <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39  dcall
Handler: "onTap"
Recognizer: TapGestureRecognizer#ee2a1
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(44.6, 94.0)
  finalLocalPosition: Offset(20.6, 10.0)
  button: 1
  sent tap down
====================================================================================================

```

Here is a minimum reproducible example

```dart
import 'package:flutter/material.dart';
import 'package:collapsible_sidebar/collapsible_sidebar.dart';

void main() => runApp(const WhisperApp());

class WhisperApp extends StatefulWidget {
  const WhisperApp({Key? key}) : super(key: key);

  @override
  State<WhisperApp> createState() => WhisperAppState();
}

class WhisperAppState extends State<WhisperApp> {
  @override
  void initState() {
    super.initState();
  }

  List<CollapsibleItem> get sidebarItems {
    return [
      CollapsibleItem(
        text: "Home",
        onPressed: () => print("home"),
        icon: Icons.home,
      ),
      CollapsibleItem(
        text: "Paths",
        onPressed: () => print("paths"),
        icon: Icons.folder,
      ),
      CollapsibleItem(
        text: "Settings",
        onPressed: () => print("settings"),
        icon: Icons.settings,
      ),
    ];
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark(),
      home: SafeArea(
        child: Scaffold(
          body: CollapsibleSidebar(
            items: sidebarItems,
            showTitle: false,
            body: const Center(child: Text("Home")),
          ),
        ),
      ),
    );
  }
}

```

**Comment by JoshLoecker** [comment]
This is my `pubspec.yaml`

```yaml
name: whisper_ui
description: A web interface for WhisperCPP
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  collapsible_sidebar: ^2.0.5+1
  http: ^0.13.6
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  riverpod_generator: ^2.2.3
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
```
